# set schedule build as Crontab expression: 0 22 * * *
version: '{build}'
image: WMF 5

environment:
  #Github credentials - used to save result to gist and to commit pushed packages to the git repository
  github_user: codingsteff
  github_pass:
    secure: aR/96vopxYpHbL9tChgOiw==
  github_api_key:
    secure: ggaXNMEdEIn7XOgV4MsEDnZ1N0ycdSPte/BUCwFTv/5NRPOTz8Pj1zgP9cRbfBq4 # Token: public_repo + gist

  #ID of the gist used to save run results
  github_gist_id: 11d4abbe6bb1fcd50426bad5b7ea88de

  #Gmail credentials - for error notifications
  mail_user: coding.steff.dev@gmail.com
  mail_pass:
    secure: aR/96vopxYpHbL9tChgOiw==
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  #Chocolatey API key - to push updated packages
  api_key:
    secure: CcmSHQ2lL0R5cVlLFCG/vTgXXfGpJV5VbNbS65z9Bvw94XxCrUqLmED+AW/jYLMP

init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- choco --version
- ps: |
    git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
    . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version
- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

build_script:
- ps: c:/projects/chocolatey-packages/update_all.ps1

artifacts:
- path: update_info.xml

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true