version: '{build}'
image: WMF 5

environment:
  #Github credentials - used to save result to gist and to commit pushed packages to the git repository
  github_user: codingsteff
  github_pass:
    secure: aR/96vopxYpHbL9tChgOiw==
  github_api_key:
    secure: W+Khh+y60tjshEKVg7Cqr4i+SrL2tjxx6VSQZ3tpxD4UPh9+IBO+ro/kDhlKRURW

  #ID of the gist used to save run results
  github_gist_id: 11d4abbe6bb1fcd50426bad5b7ea88de

  #Gmail credentials - for error notifications
  mail_user: coding.steff.dev@gmail.com
  mail_pass:
    secure: aR/96vopxYpHbL9tChgOiw==

  #Chocolatey API key - to push updated packages
  api_key:
    secure: CcmSHQ2lL0R5cVlLFCG/vTgXXfGpJV5VbNbS65z9Bvw94XxCrUqLmED+AW/jYLMP

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- gem install gist --no-ri --no-rdoc
- "ruby -e \"require 'gist'; Gist.login! username: ENV['github_user'], password: ENV['github_pass'] if ENV['github_user'] \""
- ps: |
    "machine github.com", "login $Env:github_user", "password $Env:github_pass" | Out-File ~/_netrc -Encoding ascii
    Install-PackageProvider -Name NuGet -Force
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
    Install-Module au -Scope CurrentUser
    Get-Module au -ListAvailable | select Name, Version

build_script:
- ps: c:/projects/chocolatey-packages/update_all.ps1

artifacts:
- path: update_info.xml
- path: gist.md

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true